version: '3.8'

services:

  detector:
    container_name: detector.py
    build:
      context: .
    environment:
      ROBOFLOW_VERSION: ${ROBOFLOW_VERSION}
      RASPBERRY_KEY: ${RASPBERRY_KEY}
      DETECOTR_ID: ${DETECTOR_ID}
    volumes:
      - ./src/picture:/app/picture