version: '3.8'

services:

  detector:
    container_name: detector
    build:
      context: .
    environment:
      LONGITUDE: ${LONGITUDE}
      LATITUDE: ${LATITUDE}
      CITY: ${CITY}
      TYPE_OF_VIDEO: ${TYPE_OF_VIDEO}
      ROBOFLOW_VERSION : ${ROBOFLOW_VERSION}
      RASPBERRY_KEY: ${RASPBERRY_KEY}
    volumes:
      - ./api:/python-docker