on:
  pull_request:
    branches:
      - master
  push:
    branches:
      -master


jobs:
  lint-python:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.12

      - name: Install Python dependencies
        run: pip install flake8

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          flake8: true